"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import { useAdminPosts } from "@/hooks/useApi";
import {
	ChevronLeft,
	ChevronRight,
	ExternalLink,
	Sparkles,
} from "lucide-react";

function formatRelative(iso: string): string {
	const diff = Date.now() - new Date(iso).getTime();
	const mins = Math.floor(diff / 60000);
	if (mins < 1) return "Just now";
	if (mins < 60) return `${mins}m ago`;
	const hours = Math.floor(mins / 60);
	if (hours < 24) return `${hours}h ago`;
	const days = Math.floor(hours / 24);
	return `${days}d ago`;
}

export default function AgentDraftsPage() {
	const [page, setPage] = useState(1);
	const limit = 20;

	const { data, isLoading } = useAdminPosts({
		page,
		limit,
		status: "draft",
		is_agent_authored: true,
	});

	const items = data?.items ?? [];
	const totalPages = data?.pages ?? 1;
	const noDrafts = !isLoading && items.length === 0;

	const handlePrev = useCallback(() => {
		setPage((p) => Math.max(1, p - 1));
	}, []);

	const handleNext = useCallback(() => {
		setPage((p) => Math.min(totalPages, p + 1));
	}, [totalPages]);

	return (
		<div className="flex flex-col gap-0 max-w-(--breakpoint-lg) mx-auto w-full p-6">
			{/* Header */}
			<div className="flex flex-col gap-2 mb-8">
				<h1 className="m-0 font-display text-h2 font-bold text-text-primary">
					Agent Drafts
				</h1>
				<p className="m-0 font-display text-body-sm text-text-secondary">
					Review and publish drafts generated by the AI agent.
				</p>
			</div>

			{isLoading ? (
				<div className="flex flex-col gap-3">
					{[...Array(5)].map((_, i) => (
						<div key={i} className="skeleton h-24 w-full rounded-lg" />
					))}
				</div>
			) : noDrafts ? (
				<div className="rounded-lg border border-border-subtle bg-bg-surface p-10 text-center">
					<div className="flex flex-col items-center gap-3">
						<Sparkles size={32} className="text-text-tertiary" />
						<p className="m-0 font-display text-body-sm text-text-secondary">
							No agent drafts yet. Trigger a run from{" "}
							<Link
								href="/admin/settings/agent"
								className="text-accent hover:underline"
							>
								Agent Settings
							</Link>
							.
						</p>
					</div>
				</div>
			) : (
				<>
					<div className="flex flex-col gap-3">
						{items.map((draft) => (
							<div
								key={draft.id}
								className="rounded-lg border border-border-subtle bg-bg-surface p-5 transition-colors hover:bg-bg-elevated/50"
							>
								<div className="flex items-start justify-between gap-4">
									<div className="min-w-0 flex-1">
										<h3 className="m-0 font-display text-h4 font-semibold text-text-primary truncate">
											{draft.title}
										</h3>
										<p className="m-0 mt-1 font-display text-body-sm text-text-secondary line-clamp-2">
											{draft.excerpt ?? "No excerpt"}
										</p>
										<div className="flex items-center gap-3 mt-3">
											<span className="font-mono text-xs text-text-tertiary">
												Created {formatRelative(draft.created_at)}
											</span>
											{draft.category && (
												<span className="rounded-sm bg-accent-muted px-2 py-0.5 font-mono text-xs text-accent">
													{draft.category.name}
												</span>
											)}
											{draft.reading_time_mins && (
												<span className="font-mono text-xs text-text-tertiary">
													{draft.reading_time_mins} min read
												</span>
											)}
										</div>
									</div>
									<Link
										href={`/admin/agent-drafts/${draft.id}`}
										className="btn-primary inline-flex items-center gap-2 no-underline shrink-0"
									>
										Review
										<ExternalLink size={14} />
									</Link>
								</div>
							</div>
						))}
					</div>

					{totalPages > 1 && (
						<div className="flex items-center justify-between mt-4">
							<p className="m-0 font-mono text-xs text-text-secondary">
								Page {page} of {totalPages}
							</p>
							<div className="flex items-center gap-2">
								<button
									type="button"
									onClick={handlePrev}
									disabled={!handlePrev}
									className="btn-ghost cursor-pointer inline-flex items-center gap-1 disabled:opacity-40 disabled:cursor-not-allowed"
								>
									<ChevronLeft size={14} />
									Previous
								</button>
								<button
									type="button"
									onClick={handleNext}
									disabled={!handleNext}
									className="btn-ghost cursor-pointer inline-flex items-center gap-1 disabled:opacity-40 disabled:cursor-not-allowed"
								>
									Next
									<ChevronRight size={14} />
								</button>
							</div>
						</div>
					)}
				</>
			)}
		</div>
	);
}
