"""add series table and post series fields

Revision ID: 014950d06b09
Revises: c925f6d2363f
Create Date: 2026-04-27 11:52:43.352995
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '014950d06b09'
down_revision: Union[str, None] = 'c925f6d2363f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_series_owner_id_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('slug', name=op.f('uq_series_slug'))
    )
    op.add_column('posts', sa.Column('series_id', sa.Uuid(), nullable=True))
    op.add_column('posts', sa.Column('series_order', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_posts_series_id_series'), 'posts', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posts_series_id_series'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'series_order')
    op.drop_column('posts', 'series_id')
    op.drop_table('series')
    # ### end Alembic commands ###
