"""add performance indexes

Revision ID: a6f3ec3ae2dd
Revises: 014950d06b09
Create Date: 2026-05-03 23:13:13.609968
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a6f3ec3ae2dd'
down_revision: Union[str, None] = '014950d06b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_owner_id'), 'categories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_index(op.f('ix_post_tags_post_id'), 'post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tags_tag_id'), 'post_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_posts_series_id'), 'posts', ['series_id'], unique=False)
    op.create_index('ix_posts_status_deleted_published', 'posts', ['status', 'deleted_at', 'published_at'], unique=False)
    op.create_index(op.f('ix_series_owner_id'), 'series', ['owner_id'], unique=False)
    op.create_index(op.f('ix_series_status'), 'series', ['status'], unique=False)
    op.create_index(op.f('ix_tags_owner_id'), 'tags', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_owner_id'), table_name='tags')
    op.drop_index(op.f('ix_series_status'), table_name='series')
    op.drop_index(op.f('ix_series_owner_id'), table_name='series')
    op.drop_index('ix_posts_status_deleted_published', table_name='posts')
    op.drop_index(op.f('ix_posts_series_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_index(op.f('ix_post_tags_tag_id'), table_name='post_tags')
    op.drop_index(op.f('ix_post_tags_post_id'), table_name='post_tags')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_categories_owner_id'), table_name='categories')
    # ### end Alembic commands ###
