"""update user_context fields

Revision ID: b2932a51c440
Revises: b7e2f4a91c03
Create Date: 2026-06-06 11:46:17.412547
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b2932a51c440'
down_revision: Union[str, None] = 'b7e2f4a91c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_embeddings_post_id'), 'post_embeddings', ['post_id'], unique=False)
    op.add_column('user_context', sa.Column('learning_focus', sa.Text(), nullable=True))
    op.add_column('user_context', sa.Column('lifestyle_context', sa.Text(), nullable=True))
    op.drop_column('user_context', 'tone_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_context', sa.Column('tone_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_context', 'lifestyle_context')
    op.drop_column('user_context', 'learning_focus')
    op.drop_index(op.f('ix_post_embeddings_post_id'), table_name='post_embeddings')
    # ### end Alembic commands ###
